// source: amusementPost.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var post_pb = require('./post_pb.js');
goog.object.extend(proto, post_pb);
goog.exportSymbol('proto.amusementPost.AmusementPost', null, global);
goog.exportSymbol('proto.amusementPost.GameType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.amusementPost.AmusementPost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.amusementPost.AmusementPost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.amusementPost.AmusementPost.displayName = 'proto.amusementPost.AmusementPost';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.amusementPost.AmusementPost.prototype.toObject = function(opt_includeInstance) {
  return proto.amusementPost.AmusementPost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.amusementPost.AmusementPost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amusementPost.AmusementPost.toObject = function(includeInstance, msg) {
  var f, obj = {
    post: (f = msg.getPost()) && post_pb.Post.toObject(includeInstance, f),
    peopleAll: jspb.Message.getFieldWithDefault(msg, 2, 0),
    peopleAlready: jspb.Message.getFieldWithDefault(msg, 3, 0),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    time: jspb.Message.getFieldWithDefault(msg, 5, 0),
    place: jspb.Message.getFieldWithDefault(msg, 6, ""),
    contact: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.amusementPost.AmusementPost}
 */
proto.amusementPost.AmusementPost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.amusementPost.AmusementPost;
  return proto.amusementPost.AmusementPost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.amusementPost.AmusementPost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.amusementPost.AmusementPost}
 */
proto.amusementPost.AmusementPost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new post_pb.Post;
      reader.readMessage(value,post_pb.Post.deserializeBinaryFromReader);
      msg.setPost(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPeopleAll(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPeopleAlready(value);
      break;
    case 4:
      var value = /** @type {!proto.amusementPost.GameType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlace(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setContact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.amusementPost.AmusementPost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.amusementPost.AmusementPost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.amusementPost.AmusementPost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.amusementPost.AmusementPost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPost();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      post_pb.Post.serializeBinaryToWriter
    );
  }
  f = message.getPeopleAll();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPeopleAlready();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTime();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getPlace();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getContact();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional post.Post post = 1;
 * @return {?proto.post.Post}
 */
proto.amusementPost.AmusementPost.prototype.getPost = function() {
  return /** @type{?proto.post.Post} */ (
    jspb.Message.getWrapperField(this, post_pb.Post, 1));
};


/**
 * @param {?proto.post.Post|undefined} value
 * @return {!proto.amusementPost.AmusementPost} returns this
*/
proto.amusementPost.AmusementPost.prototype.setPost = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.amusementPost.AmusementPost} returns this
 */
proto.amusementPost.AmusementPost.prototype.clearPost = function() {
  return this.setPost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.amusementPost.AmusementPost.prototype.hasPost = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 people_all = 2;
 * @return {number}
 */
proto.amusementPost.AmusementPost.prototype.getPeopleAll = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.amusementPost.AmusementPost} returns this
 */
proto.amusementPost.AmusementPost.prototype.setPeopleAll = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 people_already = 3;
 * @return {number}
 */
proto.amusementPost.AmusementPost.prototype.getPeopleAlready = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.amusementPost.AmusementPost} returns this
 */
proto.amusementPost.AmusementPost.prototype.setPeopleAlready = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional GameType type = 4;
 * @return {!proto.amusementPost.GameType}
 */
proto.amusementPost.AmusementPost.prototype.getType = function() {
  return /** @type {!proto.amusementPost.GameType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.amusementPost.GameType} value
 * @return {!proto.amusementPost.AmusementPost} returns this
 */
proto.amusementPost.AmusementPost.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional int32 time = 5;
 * @return {number}
 */
proto.amusementPost.AmusementPost.prototype.getTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.amusementPost.AmusementPost} returns this
 */
proto.amusementPost.AmusementPost.prototype.setTime = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string place = 6;
 * @return {string}
 */
proto.amusementPost.AmusementPost.prototype.getPlace = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.amusementPost.AmusementPost} returns this
 */
proto.amusementPost.AmusementPost.prototype.setPlace = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string contact = 7;
 * @return {string}
 */
proto.amusementPost.AmusementPost.prototype.getContact = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.amusementPost.AmusementPost} returns this
 */
proto.amusementPost.AmusementPost.prototype.setContact = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * @enum {number}
 */
proto.amusementPost.GameType = {
  WOLFKILL: 0,
  JVBEN: 1,
  BLOODTOWER: 2,
  KARAOK: 3,
  BOARDGAME: 4,
  SPORTS: 5,
  RIDING: 6,
  OTHER: 7
};

goog.object.extend(exports, proto.amusementPost);
