// source: sellPost.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var post_pb = require('./post_pb.js');
goog.object.extend(proto, post_pb);
goog.exportSymbol('proto.sellPost.GoodsType', null, global);
goog.exportSymbol('proto.sellPost.SellPost', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.sellPost.SellPost = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.sellPost.SellPost, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.sellPost.SellPost.displayName = 'proto.sellPost.SellPost';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.sellPost.SellPost.prototype.toObject = function(opt_includeInstance) {
  return proto.sellPost.SellPost.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.sellPost.SellPost} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sellPost.SellPost.toObject = function(includeInstance, msg) {
  var f, obj = {
    post: (f = msg.getPost()) && post_pb.Post.toObject(includeInstance, f),
    contact: jspb.Message.getFieldWithDefault(msg, 2, ""),
    price: jspb.Message.getFieldWithDefault(msg, 3, 0),
    goodsType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    sold: jspb.Message.getBooleanFieldWithDefault(msg, 5, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.sellPost.SellPost}
 */
proto.sellPost.SellPost.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.sellPost.SellPost;
  return proto.sellPost.SellPost.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.sellPost.SellPost} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.sellPost.SellPost}
 */
proto.sellPost.SellPost.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new post_pb.Post;
      reader.readMessage(value,post_pb.Post.deserializeBinaryFromReader);
      msg.setPost(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContact(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPrice(value);
      break;
    case 4:
      var value = /** @type {!proto.sellPost.GoodsType} */ (reader.readEnum());
      msg.setGoodsType(value);
      break;
    case 5:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSold(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.sellPost.SellPost.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.sellPost.SellPost.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.sellPost.SellPost} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.sellPost.SellPost.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPost();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      post_pb.Post.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getGoodsType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getSold();
  if (f) {
    writer.writeBool(
      5,
      f
    );
  }
};


/**
 * optional post.Post post = 1;
 * @return {?proto.post.Post}
 */
proto.sellPost.SellPost.prototype.getPost = function() {
  return /** @type{?proto.post.Post} */ (
    jspb.Message.getWrapperField(this, post_pb.Post, 1));
};


/**
 * @param {?proto.post.Post|undefined} value
 * @return {!proto.sellPost.SellPost} returns this
*/
proto.sellPost.SellPost.prototype.setPost = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.sellPost.SellPost} returns this
 */
proto.sellPost.SellPost.prototype.clearPost = function() {
  return this.setPost(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sellPost.SellPost.prototype.hasPost = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string contact = 2;
 * @return {string}
 */
proto.sellPost.SellPost.prototype.getContact = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.sellPost.SellPost} returns this
 */
proto.sellPost.SellPost.prototype.setContact = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.sellPost.SellPost} returns this
 */
proto.sellPost.SellPost.prototype.clearContact = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.sellPost.SellPost.prototype.hasContact = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 price = 3;
 * @return {number}
 */
proto.sellPost.SellPost.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.sellPost.SellPost} returns this
 */
proto.sellPost.SellPost.prototype.setPrice = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional GoodsType goods_type = 4;
 * @return {!proto.sellPost.GoodsType}
 */
proto.sellPost.SellPost.prototype.getGoodsType = function() {
  return /** @type {!proto.sellPost.GoodsType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.sellPost.GoodsType} value
 * @return {!proto.sellPost.SellPost} returns this
 */
proto.sellPost.SellPost.prototype.setGoodsType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional bool sold = 5;
 * @return {boolean}
 */
proto.sellPost.SellPost.prototype.getSold = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 5, false));
};


/**
 * @param {boolean} value
 * @return {!proto.sellPost.SellPost} returns this
 */
proto.sellPost.SellPost.prototype.setSold = function(value) {
  return jspb.Message.setProto3BooleanField(this, 5, value);
};


/**
 * @enum {number}
 */
proto.sellPost.GoodsType = {
  TICKET: 0,
  BOOK: 1,
  DISPLAY: 2,
  COMPUTER: 3,
  OTHER: 4
};

goog.object.extend(exports, proto.sellPost);
